export enum EFetchPhones {
  FETCH_PHONES_PENDING = 'FETCH_PHONES_PENDING',
  FETCH_PHONES_SUCCESS = 'FETCH_PHONES_SUCCESS',
  FETCH_PHONES_FAILURE = 'FETCH_PHONES_FAILURE',
}

export enum ELoadMorePhones {
  LOAD_MORE_PHONES_PENDING = 'LOAD_MORE_PHONES_PENDING',
  LOAD_MORE_PHONES_SUCCESS = 'LOAD_MORE_PHONES_SUCCESS',
  LOAD_MORE_PHONES_FAILURE = 'LOAD_MORE_PHONES_FAILURE',
}

export enum EFetchPhoneById {
  FETCH_PHONE_BY_ID_PENDING = 'FETCH_PHONE_BY_ID_PENDING',
  FETCH_PHONE_BY_ID_SUCCESS = 'FETCH_PHONE_BY_ID_SUCCESS',
  FETCH_PHONE_BY_ID_FAILURE = 'FETCH_PHONE_BY_ID_FAILURE',
}

export enum EAddPhoneToBasket {
  ADD_PHONE_TO_BASKET = 'ADD_PHONE_TO_BASKET',
}
